# site_name: "â–€â–„â–€â–„â–€â–„ğŸ…ƒğŸ…ƒğŸ…ƒ ğŸ„³ğŸ„¾ğŸ„²ğŸ…‚â–€â–„â–€â–„â–€â–„"
# site_name: "ğŸ‡¹ ğŸ‡¹ ğŸ‡¹  ğŸ‡© ğŸ‡´ ğŸ‡¨ ğŸ‡¸"
# site_name: "â–ˆâ–“â–’Â­â–‘â¡·â ‚ğŸ‡¹ ğŸ‡¹ ğŸ‡¹ DĞ¤CSâ â¢¾â–‘â–’â–“â–ˆ"
# site_name: "ğŸ†ƒğŸ†ƒğŸ†ƒ Â· ğŸ…³ğŸ…¾ğŸ…²ğŸ†‚"
site_name: "ğŸ‡¹ ğŸ‡¹ ğŸ‡¹ Â· ğŸ‡© ğŸ‡´ ğŸ‡¨ ğŸ‡¸"
site_author: cApStAn TTT
site_url: https://capstanlqc.github.com/ttt_docs
nav:
  - Projects:
      - Projects: projects/index.md
      - â˜… Flash:
          - ğŸ‘¤ Automated workflow: projects/flash/flash_automation.md
          - â˜† Automation diagram: projects/flash/flowchart.md
          - â˜† Style guide [pl-PL]: projects/flash/FLASH_style-guide_pol-POL.md
      - â˜… PISA 2025:
          - projects/pisa/index.md
          - projects/pisa/errors.md
          - â˜† projects/pisa/trainings.md
          - ğŸ‘¤ Trend transfer: projects/pisa/pisa2025_trend-transfer_guide.md
      - â˜… IPSOS:
          - projects/ipsos/index.md
          - ğŸ‘¤ Workflow automation: projects/ipsos/workflow_automation.md
      - â˜… YSC:
          - projects/ysc/index.md
          - Project setup: projects/ysc/project-setup.md
          - Gender adaptation: projects/ysc/gender-adaptation.md

  - L10n tools:
      - L10n Tools: tools/index.md
      - â˜… Okapi:
          - tools/okapi/index.md
          - tools/okapi/filters.md
      - â˜… OmegaT:
          - tools/omegat/building.md
          - tools/omegat/mk-win64-jre-signed-omegat-installer.md
          - Custom configuration:
              - Customization roadmap: tools/omegat/omt_custom_roadmap.md
              - Customation howto: tools/omegat/omt_custom_tech.md
              - Spell checking: tools/omegat/hunspell.md
          - Extensions / add-ons:
              - tools/omegat/scripts.md
              - Customization script (5x): tools/omegat/omt_custom_tech.md
              - Obtain TA report: tools/omegat/mk_translatability_report_omt.md
              - tools/omegat/plugins.md
              - tools/omegat/LQE.md
              - ğŸ‘¤ !T&A notes: tools/omegat/mk_ta_notes_omt.md
              - ğŸ‘¤ !T&A notes [Comments]: tools/omegat/ta_notes.md
          - Support:
              - tools/omegat/errors.md
              - Recommended fonts: tools/omegat/fonts.md
          - Project administration:
              - tools/omegat/omt2xliff.md
              - â˜† Reconciliation packages: tools/omegat/99_automation.md
              - tools/omegat/team_projects.md
              - â˜† Team project troubleshoot: tools/omegat/team_projects_trblsht.md
          - Testing:
              - tools/omegat/pisa25_omegat_test01.md
              - tools/omegat/omegat5_testing.md
              - tools/omegat/omegat5_testing_adhoc.md
          - Tips and tricks:
              - tools/omegat/autotext.md
              - No-break spaces: tools/omegat/nbsp.md
          - TO SORT:
              - tools/omegat/pisa25_omegat_teamproj_steps.md
              - Customization ADD 2 GUIDES: tools/omegat/omt_custom_user.md
              - Download git ADD 2 GUIDES: tools/omegat/omt_team_steps4xlat.md
      - â˜… Auxiliary tools: aux-tools.md
      - â˜… Tickets: tools/tickets/omegat-tickets.md
  - Tech:
      - Tech: tech/index.md
      - ğŸ‘¤ Create folder structure: tech/mk_dir_strukt.md
      - tech/oneliners.md
      - tech/support.md
      - Utilities: tech/utils.md
      - Convert multilingual Excel to TMX: tech/xls2tmx.md
      - How to update these docs: tech/update-docs.md
      - How to share a doc in KS: tech/share-in-ks.md
  - cApps:
      - cApps: capps/index.md
      - â˜† Langtags: capps/langtags.md
      - â˜† VeryFire: capps/veryfire.md
      - â˜† VF4TA: capps/vf4ta.md
      - â˜† MemoryLn: capps/memoryln.md
      - â˜† MemoryLn TM management: capps/memoryln_tm_mngmt.md
      - â˜† xDiff: capps/xdiff.md
      - â˜† xDiff automation: capps/xdiff_automation.md
  - i18n guides:
      - i18n guides: i18n/index.md
      - â˜† XLIFF preparation: i18n/xliff-prepp-best-practices.md
      - â˜† Authoring tips: i18n/authoring-tips.md
      - â˜† Markdown (CG example): i18n/trend_math_cg_6b.md
      - Text wrapping: i18n/wrapping.md
      - â˜† Hyphenation: i18n/hyphenation.md
      - List sorting: i18n/sorting.md
      - Block formatting: i18n/formatting.md
      #      - â˜† Flip+: i18n/flip-plus.md
      - â˜† Single-source multiple-channel: i18n/ssmc.md
  - Docs for users (symlink to KS):
      - ğŸ‘¤ Wordcount analysis in Ur: tools/omegat/omt_wc.md
theme:
  name: material
  logo: _assets/img/cApStAn_symbolesensemble_blanc.png
  favicon: _assets/favicon.ico
  palette:
    # Palette: default
    - media: "(prefers-color-scheme)"
      scheme: capstan
      primary: midnight-blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: capstan
      primary: midnight-blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to dark-mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: midnight-blue
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to light-mode
  features:
    - navigation.path ## doesn't work!
    ## - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - navigation.sections
    ## - navigation.tabs
    #- navigation.tabs.sticky
    ##- navigation.expand
    - toc.follow
    - navigation.indexes
    - content.footnote.tooltips
    - "hidden": "tech"
markdown_extensions:
  - toc:
      #baselevel: 2
      permalink: True
      separator: "-"
      toc_depth: 1-3
  - attr_list
  - md_in_html
  - tables
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - _assets/css/extra.css
extra_javascript:
  - _assets/js/extra.js
# extra:
#   username: "admin"
#   password: "secret"
plugins:
  #- with-pdf
  - search
  - exclude-search:
      exclude:
        - page.md
        - page.md#section
        - share/*
        - /*/page.md
  - awesome-pages
    # - search: {}
    # - encryptcontent:
    #     global_password: 'your_password'
  - tags:
      tags_file: profiles.md
      # tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # tags_allowed:
      #   - Audienceê‰Tech
      #   - Audienceê‰User
  - macros:
      verbose: true
      include_dir: docs/_includes
copyright: Copyright &copy; 2024 cApStAn
extra:
  generator: false
